### ISSUE TITLE
Sidebar doesn't toggle with Firefox

### ISSUE THREAD

**Issue by hlb8122** [jhildenbiddle/docsify-themeable#14] opened 2019-02-08 10:11 UTC
When using the latest version of Firefox the sidebar toggle button doesn't work.

It is reproducible on the example page https://jhildenbiddle.github.io/docsify-themeable

**Comment by jhildenbiddle** [comment] 2019-02-08 17:27
This is a duplicate of #13 which I will address today.

Thanks for filing the issue, @hlb8122.

**Closed as completed by jhildenbiddle** 2019-02-08 17:27 UTC
Labels: duplicate
