### ISSUE TITLE
[feature] RTL layout

### ISSUE THREAD

**Issue by trusktr** [jhildenbiddle/docsify-themeable#43] opened 2020-05-10 02:29 UTC
Someone asked about a right-to-left layout option [here](https://gitter.im/docsifyjs/Lobby?at=5eb6b7b3347bd61630662aad). This doesn't exist in Docsify yet.

I wonder if it is possible as a pure-CSS variable option here in docsify-themeable. I'm hoping we may not need to make structural HTML changes or modify JS to achieve this.

Docsify-themeable has by far the most control over Docsify theming, so I thought you may have insights on how possible this is. :)

**Comment by jhildenbiddle** [comment] 2020-05-10 21:32
It's certainly possible. 

If given the choice, I'd prefer to make this a native feature in docsify v5 (with an updated version of docsify-themeable that implements RTL layouts) than hack it into docsify v4. The reason for this is that the existing v4 markup structure will require hacks to make an RTL layout work properly. If we know from the beginning that RTL layouts are a requirement for v5, we can adjust the markup structure accordingly and the code to support RTL layouts will be much easier to implement and maintain.

**Comment by trusktr** [comment] 2020-05-14 03:08
> structure will require hacks to make an RTL layout work properly

What hacks do you imagine? Or i.e. what would we change for a major version to make the Docsify markup more robust in your opinion?

**Comment by jhildenbiddle** [comment] 2020-05-14 06:30
In order move docsify forward, address some well known bugs, and add new features (like RTL layouts) I believe the markup generated by docsify should be revisited as well as the supporting CSS, with the results being released as part of docsify v5.

The CSS currently used by docsify and docsify-themeable was designed for compatibility with IE10+ due to docsify's original compatibility claims (even though IE10 was always pretty rough). As a result, the supporting CSS does not leverage modern layout techniques like flexbox or CSS grid, nor is the markup optimized for these techniques. Can we make RTL layouts work in v4? Sure. Should we? I personally don't think so, as this seems more like a feature we can take into account while revisiting docsify's HTML & CSS on the road to v5.

Just my $0.02.

**Comment by jhildenbiddle** [comment] 2020-05-14 06:32
BTW, I noticed there is a [docsify-rtl](https://github.com/ckoliber/docsify-rtl) plugin on [awesome-docsify](https://github.com/docsifyjs/awesome-docsify#plugins). I've never tried it, but perhaps this could be useful for v4 users?

**Comment by trusktr** [comment] 2020-05-14 07:55
Oh interesting find. Yeah, I agree, let's move forward with any new features, and make any changes for V5+.

**Closed as completed** 2020-05-14 15:39 UTC
